### ISSUE TITLE
Not working in Atom 1.0 Linux

### ISSUE THREAD

**Issue by Janghou** [redgluten/laravel-form-bootstrap-snippets-atom#1]
Great plug-in, really helpful for fast development.
But does not work here out of the box.

I needed to change the first line of every file:
`'.text.html.php.laravel-blade':`
to 
`'.text.html.php,laravel-blade':`

`sed -i 's/text.html.php.laravel-blade/text.html.php/g' *.cson`

BTW I think you can drop laravel-blade in the selector.

And I would suggest to concatenate to 1 big file, you have to set the selector only once.

**Comment by redgluten** [comment]
I’ve already published an update, have you tried it with the 0.2.2 release?

**Comment by Janghou** [comment]
v0.2.3 does work. Thx.

**Comment by Janghou** [comment]
That said, your `email` snippet  has still a broken selector in 0.2.3. 
Don't you think 1 concatenated file is better for performance or boot time.

**Comment by redgluten** [comment]
Ok I’ll make a full review of the snippets tomorrow. As of now it’s mostly an automated port from [the package I made for Sublime Text](https://github.com/redgluten/laravel_forms_boostrap_snippets).
I’ll check the performance angle later too, thanks for your inputs. :+1:

**Comment by redgluten** [comment]
Related: did you have [language-blade](https://atom.io/packages/language-blade) package installed? It seems to only work if it is.

**Comment by Janghou** [comment]
Yes, just tweak the selector to make it work without the `language-blade`  package.
The selectors are like CSS selectors, this will work without the package

'.text.html.php.blade,.php':
