### ISSUE TITLE
Support   Laravel Collective Forms inputs 5.2version?

### ISSUE THREAD

**Issue by jayleco** [redgluten/laravel-form-bootstrap-snippets-atom#5]
Support   Laravel Collective Forms inputs 5.2version?
https://laravelcollective.com/docs/5.2/html

**Comment by redgluten** [comment]
Is it a question or a request for a change? As far as I’m aware this package should work fine with 5.2, I’m using 5.2 in my projects though I haven’t been using Atom on a regular basis since a few months.

**Comment by jayleco** [comment]
Thanks~!Great plugin!
